### ISSUE TITLE
Set up Github Actions to run tests for branches and PRs

### ISSUE THREAD

**Issue by njogz** [medic/interoperability#50] opened 2023-03-15 08:29 UTC

**Comment by andrablaj** [comment] 2023-03-15 08:38
@njogz is this the same as https://github.com/medic/interoperability/issues/15? If yes, I suggest to close the other ticket

**Comment by andrablaj** [comment] 2023-03-15 08:45
Either way works as long as we don't keep duplicated issues. I will let you make the call on this one. 😊

**Comment by andrablaj** [comment] 2023-03-21 11:33
Closing as duplicate of https://github.com/medic/interoperability/issues/15

**Closed by andrablaj** 2023-03-21 11:33 UTC
